spring.application.name=rsm_pack_and_drop
server.port=1919

spring.datasource.url=jdbc:mysql://mysql-db:3306/logistics
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true